### PR TITLE
Fix encoding issue #11

### LINKED ISSUE #11: Import Error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 103: ordinal not in range(128)
Docker container 
```bash
FROM ubuntu:18.04
RUN apt-get update --fix-missing 
RUN apt-get install -y python3 python3-pip 
RUN apt-get install -y python3 python3-pip 
RUN stopwordsiso
```

```bash
root@d92e207832a9:/# pip3 install stopwordsiso --no-cache
Collecting stopwordsiso
  Downloading https://files.pythonhosted.org/packages/81/b5/8a2544801cf6ea94b3d3bfad95c72821bbff8373277746881af93103d72d/stopwordsiso-0.5.1-py3-none-any.whl (69kB)
    100% |################################| 71kB 2.3MB/s 
Installing collected packages: stopwordsiso
Successfully installed stopwordsiso-0.5.1
root@d92e207832a9:/# python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stopwordsiso
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/stopwordsiso/__init__.py", line 14, in <module>
    _stopwords_all = json.load(json_data)
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 103: ordinal not in range(128)
>>> exit()
root@d92e207832a9:/# 
```

### PR DESCRIPTION
**Pull request by bact**
- Fix #11 - encoding issue when open JSON file
- Add docstring
- Update repo URL

### CODE REVIEW

**Comment by bact** [comment]
@genediazjr Python package is updated here https://pypi.org/project/stopwordsiso/

**Comment by bact** [comment]
@genediazjr do you mind to review this and consider a merge? thanks.

**Comment by genediazjr** [comment]
@bact sorry for the late response.

**Comment by bact** [comment]
No worries. Appreciate your time.

**Pull request merged**
